### ISSUE TITLE
Type of Website?

### ISSUE THREAD

**Issue by prydt** [PyHP-pph/pyhp-pph.github.io#1]
Should we make a Github Pages website or a custom one?

**Comment by as-com** [comment]
Maybe we should write the website in PyHP++# once there is a working interpreter and standard library. 😄

**Comment by prydt** [comment]
lol yea... but until then, I think we should just make a simple website w/
links to the subreddit.

**Comment by ghost** [comment]
Unless we have any web developers who are willing to give up time to creating a website, I think a GH Pages one is fine. But once PyHP++# has CGI support etc. we should ask GitHub to let us run it on GH Pages 😃

**Comment by prydt** [comment]
yea, i agree
